### ISSUE TITLE
Add to Clipboard not Working in Metapad

### ISSUE THREAD

**Issue by dan1982code** [nvdaes/clipContentsDesigner#5] opened 2018-12-18 15:07 UTC
Hi,

I use Metapad as my notepad replacement:
http://liquidninja.com/metapad/

It works extremely well with NVDA. But, with the clip contents addin, windows+NVDA+c says "added" but does not add the selected text.

I know that Metapad is obscure and probably few people use it, but perhaps this "bug" presents itself in other similar Notepad replacements as well.

Thank you!

**Comment by nvdaes** [comment] 2018-12-18 16:14
Thanks for your interest. I can't reproduce this bug. I have downloaded Metapad, selected text in a new file using this program, and pressed NVDA+Windows+c. Moreover, I have tested this selecting text with the review cursor pressing NVDA+Windows+f9, then moving the review cursor to mark text and then pressing NVDA+Windows+c. In both cases the text is added to the clipboard.
So, for now I can't fix this. I'm using Windows 7 with NVDA 2018.4 and clipContentsDesigner 8.7. In case you are using other add-ons which could affect text selection or if you think other add-ons or something could cause conflicts, please disable them and try again to debug the problem.

**Comment by nvdaes** [comment] 2019-08-09 10:46
I will close this. If you experiment this problem and it's related to this add-on, please reopen the issue. Thanks.

**Closed by nvdaes** 2019-08-09 10:46 UTC
